"use client";
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Mic, MapPin, ShieldCheck, Siren, Hospital, Activity, Phone, Navigation, CheckCircle2 } from 'lucide-react';
import api from '@/lib/api';

function HoldSOS({onComplete}:{onComplete:()=>void}){
  const [holding,setHolding]=useState(false); const [progress,setProgress]=useState(0); const timer=useRef<ReturnType<typeof setInterval>|null>(null);
  const start=()=>{ if(holding)return; setHolding(true); setProgress(0); if('vibrate' in navigator) navigator.vibrate(40); let p=0; timer.current=setInterval(()=>{p+=100/30;setProgress(Math.min(p,100));if(p>=100){clearInterval(timer.current!);if('vibrate'in navigator)navigator.vibrate([100,50,200]);onComplete();setHolding(false);setProgress(0)}},100)};
  const stop=()=>{if(timer.current)clearInterval(timer.current);setHolding(false);setProgress(0)};
  return <button aria-label="Hold for emergency SOS" onPointerDown={start} onPointerUp={stop} onPointerLeave={stop} onContextMenu={e=>e.preventDefault()} className="relative w-44 h-44 sm:w-52 sm:h-52 rounded-full select-none touch-none flex items-center justify-center bg-[#171719] border border-white/10 shadow-[0_20px_80px_rgba(255,59,48,.16)]">
    {holding&&<span className="absolute inset-[-14px] rounded-full border border-[#ff3b30]/50" style={{transform:`scale(${.85+progress/300})`,opacity:1-progress/100}}/>}
    <span className="absolute inset-3 rounded-full bg-[#ff3b30] shadow-[inset_0_2px_12px_rgba(255,255,255,.2),0_12px_45px_rgba(255,59,48,.3)]" style={{background:`conic-gradient(#ff3b30 ${progress}%, #b52b25 ${progress}% 100%)`}}/>
    <span className="relative z-10 flex flex-col items-center"><Siren size={30}/><span className="mt-2 text-lg font-black tracking-[.16em]">{holding?'HOLD…':'SOS'}</span><span className="text-[10px] uppercase tracking-widest opacity-80">{holding?`${Math.ceil((100-progress)/33)}s remaining`:'3-second hold'}</span></span>
  </button>
}

export default function Home(){
 const [loading,setLoading]=useState(false); const [gps,setGps]=useState('Location not locked');
 useEffect(()=>{ if('serviceWorker'in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{}); navigator.geolocation?.getCurrentPosition(()=>setGps('GPS ready'),()=>setGps('GPS permission needed'));},[]);
 const start=()=>{setLoading(true);localStorage.setItem('emefast_role','USER');location.href='/user/emergency/new'};
 return <main className="min-h-screen landing-page text-[var(--text)] pb-[env(safe-area-inset-bottom)]">
  <header className="topnav px-5 sm:px-8 py-4"><div className="max-w-6xl mx-auto flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><div className="w-10 h-10 rounded-[14px] bg-[#ff3b30] flex items-center justify-center shadow-[0_8px_28px_rgba(255,59,48,.22)]"><Activity size={21}/></div><div><b className="text-base tracking-tight">EMEFast AI</b><span className="block text-[10px] text-[var(--muted)] tracking-wider">EMERGENCY MEDICAL FAST RESPONSE</span></div></Link><div className="flex items-center gap-2"><Link href="/login" className="glass px-4 py-2.5 rounded-full text-xs font-semibold">Sign In</Link><button onClick={start} disabled={loading} className="sos-btn px-4 py-2.5 text-xs flex gap-2 items-center"><Siren size={14}/>{loading?'Starting…':'Emergency SOS'}</button></div></div></header>
  <div className="status-ticker px-5 py-2 text-[11px] text-[var(--muted)]"><div className="max-w-6xl mx-auto flex gap-5 overflow-hidden whitespace-nowrap"><span className="text-[#30d158]">● Network online</span><span>Verified emergency hospitals</span><span>Real-time resource intelligence</span><span>{gps}</span></div></div>
  <section className="max-w-6xl mx-auto px-5 sm:px-8 pt-12 sm:pt-20 pb-14 grid lg:grid-cols-[1.1fr_.9fr] gap-12 items-center">
   <div><div className="badge-red px-3 py-1.5 text-[10px] font-semibold tracking-widest mb-5">EMERGENCY RESPONSE NETWORK</div><h1 className="text-5xl sm:text-7xl font-semibold tracking-[-.055em] leading-[.95]">Seconds matter.<br/><span className="text-[#ff453a]">We coordinate.</span></h1><p className="mt-6 max-w-xl text-[var(--muted)] text-base sm:text-lg leading-relaxed">Create an emergency in seconds, match against hospital capability and resources, and keep the care team informed before arrival.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/ambulance/emergency/new" className="sos-btn px-5 py-3.5 flex items-center gap-2">Create Emergency <ArrowRight size={16}/></Link><Link href="/ambulance/dashboard" className="glass rounded-full px-5 py-3.5 text-sm font-semibold">Open Ambulance Workspace</Link></div><div className="mt-8 flex flex-wrap gap-4 text-xs text-[var(--muted)]"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#30d158]"/>Consent-first health data</span><span className="flex items-center gap-2"><MapPin size={15} className="text-[#ff9f0a]"/>GPS-assisted hospital matching</span></div></div>
   <div className="flex flex-col items-center justify-center"><HoldSOS onComplete={start}/><p className="mt-7 text-sm font-semibold">Hold to trigger emergency SOS</p><p className="mt-1 text-xs text-[var(--muted)] text-center max-w-xs">Designed to prevent accidental activation while remaining usable under stress.</p></div>
  </section>
  <section className="max-w-6xl mx-auto px-5 sm:px-8 pb-12"><div className="grid md:grid-cols-3 gap-4"><div className="v2-card p-6 v2-card-hover"><Mic className="text-[#ff453a]"/><h3 className="mt-5 font-semibold">Voice Emergency</h3><p className="mt-2 text-sm text-[var(--muted)]">Hindi + English voice capture with structured emergency fields and confirmation.</p></div><div className="v2-card p-6 v2-card-hover"><Hospital className="text-[#30d158]"/><h3 className="mt-5 font-semibold">Hospital Intelligence</h3><p className="mt-2 text-sm text-[var(--muted)]">Compare capability, resource readiness, ETA and hospital response instead of distance alone.</p></div><div className="v2-card p-6 v2-card-hover"><Navigation className="text-[#64d2ff]"/><h3 className="mt-5 font-semibold">Live Hospital Coordination</h3><p className="mt-2 text-sm text-[var(--muted)]">Hospital responses, recommendation factors, ER pre-alert and arrival states in one timeline.</p></div></div></section>
  <footer className="max-w-6xl mx-auto px-5 sm:px-8 py-6 border-t border-white/10 flex flex-wrap gap-4 justify-between text-[11px] text-[#636366]"><span>EMEFast AI · Emergency Medical Fast Response System</span><span className="flex items-center gap-2"><Phone size={12}/> 108 / 112</span></footer>
 </main>
}
