import http from 'node:http';
import { readFile, writeFile, mkdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(ROOT, 'emefast-demo.json');
const UPLOADS = path.join(ROOT, 'uploads', 'voice');
const PORT = Number(process.env.PORT || 8000);
const DEMO_MODE = String(process.env.DEMO_MODE || '0') === '1';
const allowedOrigins = String(process.env.CORS_ORIGINS || 'http://localhost:3001,https://frontend-v2-seven-chi.vercel.app').split(',').map(x=>x.trim()).filter(Boolean);
const hospitals = [
  {id:1,name:'SMS Hospital',address:'Jawahar Lal Nehru Marg, Jaipur',latitude:26.9124,longitude:75.7873,estimated_emergency_cost:2500,available_icu:8,available_beds:34,capabilities:'Emergency, Trauma, Cardiac, Neuro, Orthopedic, Pediatric, Maternity, Ventilator, ICU',contact_phone:'+91 141 2560291'},
  {id:2,name:'Fortis Hospital',address:'Malviya Nagar, Jaipur',latitude:26.8540,longitude:75.8063,estimated_emergency_cost:3000,available_icu:6,available_beds:28,capabilities:'Emergency, Trauma, Cardiac, Neuro, Orthopedic, Ventilator, ICU',contact_phone:'+91 141 2547000'},
  {id:3,name:'Narayana Hospital',address:'Pratap Nagar, Jaipur',latitude:26.8065,longitude:75.8280,estimated_emergency_cost:3500,available_icu:7,available_beds:30,capabilities:'Emergency, Trauma, Cardiac, Orthopedic, Pediatric, Ventilator, ICU',contact_phone:'+91 141 7122222'},
  {id:4,name:'Manipal Hospital',address:'Sector 5, Vidhyadhar Nagar, Jaipur',latitude:26.9638,longitude:75.7788,estimated_emergency_cost:4200,available_icu:5,available_beds:24,capabilities:'Emergency, Trauma, Cardiac, Neuro, Orthopedic, Ventilator, ICU',contact_phone:'+91 141 5165000'},
  {id:5,name:'Rukmani Birla Hospital',address:'Durgapura, Jaipur',latitude:26.8567,longitude:75.7892,estimated_emergency_cost:3900,available_icu:5,available_beds:22,capabilities:'Emergency, Trauma, Cardiac, Neuro, Maternity, Ventilator, ICU',contact_phone:'+91 141 3528888'},
  {id:6,name:'Mahaveer Cancer Hospital',address:'Jagatpura, Jaipur',latitude:26.8356,longitude:75.8245,estimated_emergency_cost:4500,available_icu:4,available_beds:20,capabilities:'Emergency, Oncology, ICU, Oxygen',contact_phone:'+91 141 2771777'},
  {id:7,name:'Eternal Hospital',address:'Jawahar Lal Nehru Marg, Jaipur',latitude:26.8958,longitude:75.8061,estimated_emergency_cost:4800,available_icu:6,available_beds:26,capabilities:'Emergency, Trauma, Cardiac, Neuro, Orthopedic, Maternity, Ventilator, ICU',contact_phone:'+91 141 4410000'}
].map(h=>({...h,verified:true,emergency_status:'ONLINE',oxygen_available:true,trauma_capability:true,emergency_capacity:50,blood_units:40}));

const seedUsers=[{id:1,name:'Ambulance Paramedic',email:'paramedic@emefast.demo',role:'USER',created_at:'2026-01-01T08:00:00.000Z'},{id:2,name:'SMS Hospital ER Lead',email:'erlead@sms-emefast.demo',role:'HOSPITAL',hospital_id:1,created_at:'2026-01-02T08:00:00.000Z'},{id:3,name:'EMEFast Network Admin',email:'admin@emefast.demo',role:'ADMIN',created_at:'2026-01-03T08:00:00.000Z'}];
const empty=()=>({nextId:1,cases:[],responses:[],audit:[],users:seedUsers});
async function load(){try{return JSON.parse(await readFile(DATA,'utf8'));}catch{return empty();}}
async function save(db){await writeFile(DATA,JSON.stringify(db,null,2));}
function corsOrigin(req){const origin=req?.headers?.origin;return origin && (allowedOrigins.includes('*') || allowedOrigins.includes(origin) || origin.endsWith('.vercel.app')) ? origin : (allowedOrigins.includes('*') ? '*' : 'null');}
function json(res,status,data,req){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':corsOrigin(req),'access-control-allow-headers':'Content-Type, Authorization, X-Voice-Transcript','access-control-allow-methods':'GET,POST,PUT,PATCH,OPTIONS','vary':'Origin'});res.end(body);}
function send(res,status,data,req){return json(res,status,data,req);}
function hav(a,b,c,d){const R=6371, p=Math.PI/180, x=(c-a)*p,y=(d-b)*p;const z=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))*100)/100;}
function eta(km){return Math.max(2,Math.round(km/35*60*1.15*10)/10);}
function caseOut(db,c){const rs=db.responses.filter(r=>r.case_id===c.id).map(r=>({...r,hospital_name:hospitals.find(h=>h.id===r.hospital_id)?.name||'Hospital',hospital_address:hospitals.find(h=>h.id===r.hospital_id)?.address||'',hospital_capabilities:hospitals.find(h=>h.id===r.hospital_id)?.capabilities||''}));const sh=hospitals.find(h=>h.id===c.selected_hospital_id);return {...c,responses:rs,selected_hospital:sh?{...sh}:null};}
function maybeAutoAccept(db,c){if(DEMO_MODE && c.autoAcceptAt && Date.now()>=c.autoAcceptAt){const pending=db.responses.filter(r=>r.case_id===c.id&&r.response==='PENDING').sort((a,b)=>a.eta-b.eta);for(const r of pending.slice(0,2)){r.response='ACCEPTED';r.responded_at=new Date().toISOString();}c.autoAcceptAt=null;if(db.responses.filter(r=>r.case_id===c.id&&r.response==='ACCEPTED').length)c.status='ACCEPTED';return true;}return false;}
function capabilities(caseObj,h){const t=((caseObj.condition||'')+' '+(caseObj.requirements||'')).toLowerCase(), caps=h.capabilities.toLowerCase(), miss=[];if((caseObj.priority==='CRITICAL'||caseObj.priority==='HIGH'||t.includes('icu'))&&h.available_icu<=0)miss.push('ICU');if(t.includes('ventilator')&&!caps.includes('ventilator'))miss.push('Ventilator');if(t.includes('oxygen')&&!h.oxygen_available)miss.push('Oxygen');if(t.includes('trauma')&&!h.trauma_capability)miss.push('Trauma');for(const [needle,cap] of [['cardiologist','cardiac'],['cardiac','cardiac'],['neurosurgeon','neuro'],['stroke','neuro'],['orthopedic','orthopedic'],['pediatric','pediatric'],['maternity','maternity']])if(t.includes(needle)&&!caps.includes(cap))miss.push(cap);return miss;}
function recommendation(db,c){maybeAutoAccept(db,c);const all=db.responses.filter(r=>r.case_id===c.id).map(r=>{const h=hospitals.find(x=>x.id===r.hospital_id), missing=capabilities(c,h), feasible=h.verified&&h.emergency_status==='ONLINE'&&h.available_beds>0&&!missing.length, cost=r.estimated_cost??h.estimated_emergency_cost, score=r.response==='ACCEPTED'&&feasible?Math.round((Math.max(0,100-Math.min(r.eta*3,100))*.5+Math.min(100,(h.available_icu||0)*10)*.25+Math.max(0,100-Math.min(cost/1000,100))*.25)*10)/10:0;return {...r,hospital_name:h.name,hospital_address:h.address,hospital_capabilities:h.capabilities,latitude:h.latitude,longitude:h.longitude,available_icu:h.available_icu,available_beds:h.available_beds,estimated_cost:cost,capability_match:feasible,is_recommended:false,score,explanation:[`Response: ${r.response}`,`ETA: ${r.eta} min`,`Estimated emergency cost: ₹${cost.toLocaleString()}`,feasible?'Eligibility: requirements currently satisfied':`Not feasible: ${missing.join(', ')||'hospital unavailable'}`]};});const accepted=all.filter(x=>x.response==='ACCEPTED'&&x.capability_match).sort((a,b)=>b.score-a.score||a.eta-b.eta||a.estimated_cost-b.estimated_cost);const rec=accepted[0]||null;if(rec)rec.is_recommended=true;return {case_id:c.id,case_code:c.case_code,recommended_hospital:rec,fastest_hospital:accepted[0]?accepted.reduce((a,b)=>a.eta<=b.eta?a:b):null,cheapest_hospital:accepted[0]?accepted.reduce((a,b)=>a.estimated_cost<=b.estimated_cost?a:b):null,all_options:all,total_evaluated:all.length,accepted_count:all.filter(x=>x.response==='ACCEPTED').length,rejected_count:all.filter(x=>x.response==='REJECTED').length,pending_count:all.filter(x=>x.response==='PENDING').length,decision_summary:rec?`Recommended ${rec.hospital_name} as the best overall accepted feasible option.`:'Awaiting hospital responses.'};}
async function body(req){return await new Promise((resolve,reject)=>{const chunks=[];req.on('data',x=>chunks.push(x));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject);});}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{},req);const u=new URL(req.url,'http://localhost');let db=await load();
 try{
  if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}
  if(u.pathname==='/api/health')return json(res,200,{status:'ONLINE'},req);
  if(req.method==='GET'&&u.pathname==='/api/hospitals')return json(res,200,hospitals,req);
  if(req.method==='GET'&&u.pathname==='/api/hospitals/verified')return json(res,200,hospitals.filter(h=>h.verified),req);
  let m=u.pathname.match(/^\/api\/hospitals\/(\d+)$/);if(req.method==='GET'&&m){const h=hospitals.find(x=>x.id==m[1]);return h?json(res,200,h,req):json(res,404,{detail:'Hospital not found'},req);}
  m=u.pathname.match(/^\/api\/hospitals\/(\d+)\/incoming$/);if(req.method==='GET'&&m){const id=Number(m[1]);const changed=db.cases.some(c=>maybeAutoAccept(db,c));if(changed)await save(db);const cases=db.cases.filter(c=>db.responses.some(r=>r.case_id===c.id&&r.hospital_id===id)&&['SEARCHING','AWAITING_RESPONSE','ACCEPTED','HOSPITAL_SELECTED','EN_ROUTE'].includes(c.status));return json(res,200,cases.map(c=>caseOut(db,c)),req);}
  m=u.pathname.match(/^\/api\/hospitals\/(\d+)\/active-cases$/);if(req.method==='GET'&&m){const id=Number(m[1]);return json(res,200,db.cases.filter(c=>db.responses.some(r=>r.case_id===c.id&&r.hospital_id===id&&['ACCEPTED','SELECTED'].includes(r.response))).map(c=>caseOut(db,c)),req);}
  m=u.pathname.match(/^\/api\/hospitals\/(\d+)\/respond\/(\d+)$/);if(req.method==='POST'&&m){const raw=await body(req);const q=JSON.parse(raw||'{}'),r=db.responses.find(x=>x.hospital_id==m[1]&&x.case_id==m[2]),c=db.cases.find(x=>x.id==m[2]);if(!r||!c)return json(res,404,{detail:'Emergency query not found'},req);if(q.response==='REJECTED'&&!q.rejection_reason)return json(res,400,{detail:'Rejection reason is required'},req);r.response=q.response;r.rejection_reason=q.rejection_reason||null;r.eta=q.eta??r.eta;r.responded_at=new Date().toISOString();if(r.response==='ACCEPTED')c.status='ACCEPTED';await save(db);return json(res,200,{status:'success',case_id:c.id,case_code:c.case_code,hospital_id:r.hospital_id,response:r.response,eta:r.eta,rejection_reason:r.rejection_reason},req);}
  if(req.method==='POST'&&u.pathname==='/api/emergency/new'){const q=JSON.parse(await body(req));const id=db.nextId++;const c={id,case_code:`EME-${String(id).padStart(4,'0')}`,user_id:null,patient_name:q.patient_name||'Unknown Patient',patient_age:q.patient_age??null,abha_id:q.abha_id??null,transport_mode:q.transport_mode||'AMBULANCE',condition:q.condition||'Emergency — details pending',priority:q.priority||'HIGH',requirements:q.requirements||'Emergency stabilization',vitals:q.vitals??null,latitude:Number(q.latitude),longitude:Number(q.longitude),address:q.address||'GPS location',ambulance_details:q.ambulance_details??null,status:'AWAITING_RESPONSE',selected_hospital_id:null,selected_hospital_eta:null,description:q.description??null,voice_note_path:null,voice_transcript:q.voice_transcript||null,created_at:new Date().toISOString(),autoAcceptAt:DEMO_MODE ? Date.now()+2500 : null};db.cases.unshift(c);for(const h of hospitals){const d=hav(c.latitude,c.longitude,h.latitude,h.longitude);db.responses.push({id:db.responses.length+1,case_id:id,hospital_id:h.id,response:'PENDING',rejection_reason:null,eta:eta(d),distance_km:d,estimated_cost:h.estimated_emergency_cost,responded_at:null});}db.audit.unshift({case_id:id,performed_by:c.patient_name,action:'EMERGENCY_CREATED',details:`Broadcast to ${hospitals.length} verified hospitals`,timestamp:new Date().toISOString()});await save(db);return json(res,200,caseOut(db,c),req);}
  if(req.method==='GET'&&u.pathname==='/api/emergency/active/current'){const c=db.cases.find(x=>['SEARCHING','AWAITING_RESPONSE','ACCEPTED','HOSPITAL_SELECTED','EN_ROUTE'].includes(x.status));if(c){if(maybeAutoAccept(db,c))await save(db);return json(res,200,caseOut(db,c),req);}return json(res,200,null,req);}
  if(req.method==='GET'&&u.pathname==='/api/emergency/history/all')return json(res,200,db.cases.slice(0,50).map(c=>caseOut(db,c)),req);
  m=u.pathname.match(/^\/api\/emergency\/(\d+)$/);if(req.method==='GET'&&m){const c=db.cases.find(x=>x.id==m[1]);return c?json(res,200,caseOut(db,c),req):json(res,404,{detail:'Emergency case not found'},req);}
  m=u.pathname.match(/^\/api\/emergency\/(\d+)\/recommendation$/);if(req.method==='GET'&&m){const c=db.cases.find(x=>x.id==m[1]);if(!c)return json(res,404,{detail:'Emergency case not found'},req);const out=recommendation(db,c);await save(db);return json(res,200,out,req);}
  m=u.pathname.match(/^\/api\/emergency\/(\d+)\/select-hospital$/);if(req.method==='POST'&&m){const q=JSON.parse(await body(req)),c=db.cases.find(x=>x.id==m[1]),r=db.responses.find(x=>x.case_id==c?.id&&x.hospital_id==q.hospital_id);if(!c||!r||!['ACCEPTED','SELECTED'].includes(r.response))return json(res,409,{detail:'Hospital must accept before selection'},req);c.selected_hospital_id=r.hospital_id;c.selected_hospital_eta=r.eta;c.status='HOSPITAL_SELECTED';r.response='SELECTED';await save(db);return json(res,200,caseOut(db,c),req);}
  m=u.pathname.match(/^\/api\/emergency\/(\d+)\/voice-note$/);if(req.method==='POST'&&m){const id=Number(m[1]),c=db.cases.find(x=>x.id===id);if(!c)return json(res,404,{detail:'Emergency case not found'},req);const b=await body(req);if(!b.length)return json(res,400,{detail:'Empty voice recording'},req);await mkdir(UPLOADS,{recursive:true});if(c.voice_note_path){const previous=path.join(ROOT,c.voice_note_path.replace(/^\/api\/emergency\/\d+\/voice-note\//,''));try{await unlink(previous)}catch{}}const ext=(req.headers['content-type']||'audio/webm').split(';')[0].split('/')[1]||'webm';const file=`${c.case_code}-${randomUUID()}.${ext==='mp4'?'m4a':ext}`;await writeFile(path.join(UPLOADS,file),b);c.voice_note_path=`/api/emergency/${id}/voice-note/${file}`;c.voice_transcript=req.headers['x-voice-transcript']||c.voice_transcript||null;await save(db);return json(res,200,{status:'saved',case_id:id,voice_note_path:c.voice_note_path,transcript:c.voice_transcript},req);}
  m=u.pathname.match(/^\/api\/emergency\/(\d+)\/voice-note\/([^/]+)$/);if(req.method==='GET'&&m){const file=path.join(UPLOADS,m[2]);if(!existsSync(file))return json(res,404,{detail:'Voice note not found'},req);res.writeHead(200,{'content-type':m[2].endsWith('.m4a')?'audio/mp4':'audio/webm','access-control-allow-origin':corsOrigin(req),'vary':'Origin'});return res.end(await readFile(file));}
  if(req.method==='POST'&&u.pathname==='/api/auth/login')return json(res,200,{access_token:'demo-token',token_type:'bearer',role:'USER',user_name:'Demo User',hospital_id:null},req);
  if(req.method==='GET'&&u.pathname==='/api/admin/metrics')return json(res,200,{active_emergencies:db.cases.filter(c=>!['COMPLETED','CANCELLED'].includes(c.status)).length,verified_hospitals:hospitals.filter(h=>h.verified).length,total_hospitals:hospitals.length,available_hospitals:hospitals.filter(h=>h.verified&&h.emergency_status==='ONLINE'&&h.available_beds>0).length,cases_today:db.cases.length,avg_response_time_minutes:2.5},req);
  if(req.method==='GET'&&u.pathname==='/api/admin/emergencies')return json(res,200,db.cases.map(c=>caseOut(db,c)),req);
  if(req.method==='GET'&&u.pathname==='/api/admin/hospitals')return json(res,200,hospitals,req);
  m=u.pathname.match(/^\/api\/admin\/hospitals\/(\d+)\/verify$/);if(req.method==='PATCH'&&m){const h=hospitals.find(x=>x.id==m[1]);if(!h)return json(res,404,{detail:'Hospital not found'},req);const verify=u.searchParams.get('verify')!=='false';h.verified=verify;h.emergency_status=verify?'ONLINE':'OFFLINE';await save(db);return json(res,200,h,req);}
  if(req.method==='GET'&&u.pathname==='/api/admin/users'){if(!db.users)db.users=seedUsers;return json(res,200,db.users,req);}
  m=u.pathname.match(/^\/api\/hospitals\/(\d+)\/resources$/);if(req.method==='PATCH'&&m){const h=hospitals.find(x=>x.id==m[1]);if(!h)return json(res,404,{detail:'Hospital not found'},req);const q=JSON.parse(await body(req)||'{}');if(q.available_icu!==undefined)h.available_icu=Math.max(0,Number(q.available_icu));if(q.available_beds!==undefined)h.available_beds=Math.max(0,Number(q.available_beds));if(q.emergency_status)h.emergency_status=q.emergency_status;await save(db);return json(res,200,h,req);}
  return json(res,404,{detail:'Endpoint not found'},req);
 }catch(e){console.error(e);return json(res,500,{detail:e.message||'Server error'},req);}
});
server.listen(PORT,'0.0.0.0',()=>console.log(`EMEFast demo API listening on http://localhost:${PORT}`));
